// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNmviQvvLpxWzNQsPY36bz5ZBXSA9tNNA',
    appId: '1:809393988812:web:0eb6092fde88136ec44e69',
    messagingSenderId: '809393988812',
    projectId: 'example-twitter',
    authDomain: 'example-twitter.firebaseapp.com',
    storageBucket: 'example-twitter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjRdegwJRVHRZg5xHKnoDXmMVPUs5W3nU',
    appId: '1:809393988812:android:7dc2fe99d7c819d4c44e69',
    messagingSenderId: '809393988812',
    projectId: 'example-twitter',
    storageBucket: 'example-twitter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv_ExG_S2xIGkohMUr34Ux6oseSZAMY2E',
    appId: '1:809393988812:ios:6fba35a50e1c4353c44e69',
    messagingSenderId: '809393988812',
    projectId: 'example-twitter',
    storageBucket: 'example-twitter.firebasestorage.app',
    iosBundleId: 'com.example.twitterClient',
  );

}