name: twitter_server
description: Horda server example. Twitter clone.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  horda_server: ^0.12.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  lints: ^5.0.0
  test: ^1.24.0
