name: twitter_server
description: Horda server example. Twitter clone.
version: 0.1.2
repository: https://github.com/horda-dev/dart_examples
publish_to: https://pub.horda.dev/d368c1sgc98s738ue7cg
license: MIT

environment:
  sdk: ^3.8.1

dependencies:
  gcloud: ^0.8.19
  googleapis_auth: ^1.6.0
  horda_server: ^0.14.0
  json_annotation: ^4.9.0
  xid: ^1.2.1

dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  lints: ^5.0.0
  test: ^1.24.0
